import LocalizedStrings from "react-localization";

let strings = new LocalizedStrings(
    {
        en: {
            "login": "Login",
            "register": "Register",
            "email": "Email",
            "password": "Password",
            "reglink": "Register here",
            "firstname": "First name",
            "surname": "Surname",
            "adminuser": "Admin user",
            "teachermode": "Teacher mode",
            "showcorrect": "Show correct answers",
            "hidecorrect": "Hide correct answers",
            "question": "Question",
            "answer": "Answer",
            "addnewquestion": "Add new question",
            "addnewanswer": "Add new answer",
            "addnewquiz": "Add new quiz",
            "delete": "Delete",
            "regerror": "Registration failed",
            "files": "Files",
            "deleting": "Deleting",
            "areyousuredelete": "Are you sure you want to delete this quiz?",
            "actioncannotbeundone": "This action cannot be undone!",
            "cancel": "Cancel",
            "logout": "Logout",
            "landingtext": "Please log in or register to continue",
            "loginfail": "Login failed",
            "loginsuccess": "Login successful! Welcome",
            "registersuccess": "Registration successful! Welcome",
            "registerfail": "Registration failed",
            "greet": "Hello",
            "userinrole": "User in role",
            "language": "Language settings",
            "admin": "admin",
            "student": "student",
            "quizname": "Quiz title"
        },
        fi: {
            "login": "Kirjaudu",
            "register": "Rekisteröidy",
            "email": "Sähköposti",
            "password": "Salasana",
            "reglink": "Rekisteröidy tästä",
            "firstname": "Etunimi",
            "surname": "Sukunimi",
            "adminuser": "Admin-käyttäjä",
            "teachermode": "Opettaja",
            "showcorrect": "Näytä oikeat vastaukset",
            "hidecorrect": "Piilota oikeat vastaukset",
            "question": "Kysymys",
            "answer": "Vastaus",
            "addnewquestion": "Lisää uusi kysymys",
            "addnewanswer": "Lisää uusi vastaus",
            "addnewquiz": "Lisää uusi tentti",
            "delete": "Poista",
            "regerror": "Rekisteröityminen epäonnistui",
            "files": "Tiedostot",
            "deleting": "Poistetaan",
            "areyousuredelete": "Oletko varma, että haluat poistaa tämän tentin?",
            "actioncannotbeundone": "Tätä toimintoa ei voi peruuttaa!",
            "cancel": "Peruuta",
            "logout": "Kirjaudu ulos",
            "landingtext": "Kirjauduthan sisään jatkaaksesi",
            "loginfail": "Kirjautuminen epäonnistui",
            "loginsuccess": "Kirjautuminen onnistui! Tervetuloa",
            "registersuccess": "Rekisteröityminen onnistui! Tervetuloa",
            "registerfail": "Rekisteröityminen epäonnistui",
            "greet": "Hei",
            "userinrole": "Käyttäjä roolissa",
            "language": "Kieliasetukset",
            "admin": "admin",
            "student": "oppilas",
            "quizname": "Tentin otsikko"
        }
    }
)

export default strings